name: NEXclusive
favicon: null
layout_spectrum: 0.56254
typography_spectrum: 0.4925398910418153
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#715e9a'
    - '#dae0df'
    - '#271f1a'
    - '#be9b83'
  brandStrength: 1
  lightness: 0.2501602889969945
  saturation: 0.25
  rhythmicContrast: 0.7377951750531793
purpose: []
