name: NEXclusive
favicon: null
layout_spectrum: 0.4451206214725971
typography_spectrum: 0.4925398910418153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5907499878667295
  lightness: 0.2501602889969945
  saturation: 0.41368811251595616
  rhythmicContrast: 0.7377951750531793
purpose: []
